#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 24 11:55:13 2022

@author: yousufmohammad
"""

n = int(input())
fact=1
i=1
while i <=n:
    fact = fact*i;
    i=i + 1
    print(fact)
    
    
n = int(input()) #input() function takes input as string type
                #int() converts it to integer type
fact = 1
for i in range(1,n+1):
    fact = fact * i
print(fact)